// This file is auto generated by icy-table.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif


color_alpha * color_alpha_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key", (char *)"color"};
  static const char * const column_types[] = {"u64", "vec4"};
  color_alpha * instance = calloc(sizeof(color_alpha), 1);
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  icy_table_init((icy_table * )instance, optional_name, 2, (unsigned int[]){sizeof(u64), sizeof(vec4)}, (char *[]){(char *)"key", (char *)"color"});
  
  return instance;
}

void color_alpha_insert(color_alpha * table, u64 * key, vec4 * color, size_t count){
  void * array[] = {(void* )key, (void* )color};
  icy_table_inserts((icy_table *) table, array, count);
}

void color_alpha_set(color_alpha * table, u64 key, vec4 color){
  void * array[] = {(void* )&key, (void* )&color};
  icy_table_inserts((icy_table *) table, array, 1);
}

void color_alpha_lookup(color_alpha * table, u64 * keys, size_t * out_indexes, size_t count){
  icy_table_finds((icy_table *) table, keys, out_indexes, count);
}

void color_alpha_remove(color_alpha * table, u64 * keys, size_t key_count){
  size_t indexes[key_count];
  size_t index = 0;
  size_t cnt = 0;
  while(0 < (cnt = icy_table_iter((icy_table *) table, keys, key_count, NULL, indexes, array_count(indexes), &index))){
    icy_table_remove_indexes((icy_table *) table, indexes, cnt);
    index = 0;
  }
}

void color_alpha_clear(color_alpha * table){
  icy_table_clear((icy_table *) table);
}

void color_alpha_unset(color_alpha * table, u64 key){
  color_alpha_remove(table, &key, 1);
}

bool color_alpha_try_get(color_alpha * table, u64 * key, vec4 * color){
  void * array[] = {(void* )key, (void* )color};
  void * column_pointers[] = {(void *)table->key, (void *)table->color};
  size_t __index = 0;
  icy_table_finds((icy_table *) table, array[0], &__index, 1);
  if(__index == 0) return false;
  unsigned int sizes[] = {sizeof(u64), sizeof(vec4)};
  for(int i = 1; i < 2; i++){
    if(array[i] != NULL)
      memcpy(array[i], column_pointers[i] + __index * sizes[i], sizes[i]); 
  }
  return true;
}

void color_alpha_print(color_alpha * table){
  icy_table_print((icy_table *) table);
}

size_t color_alpha_iter(color_alpha * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator){
  return icy_table_iter((icy_table *) table, keys, keycnt, optional_keys_out, indexes, cnt, iterator);

}
