// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

id_vector * id_vector_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"key"};
  static const char * const column_types[] = {"u8"};

  id_vector * instance = calloc(sizeof(id_vector), 1);
  unsigned int sizes[] = {sizeof(u8)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 1;
  for(unsigned int i = 0; i < 1; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


id_vector_index id_vector_alloc(id_vector * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  id_vector_index index;
  index.index = idx.index;
  return index;
}

id_vector_indexes id_vector_alloc_sequence(id_vector * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  id_vector_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void id_vector_remove(id_vector * table, id_vector_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void id_vector_remove_sequence(id_vector * table, id_vector_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void id_vector_clear(id_vector * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void id_vector_optimize(id_vector * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void id_vector_destroy(id_vector ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
