// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _pid_lookup{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const pid * k1, const pid * k2);
  const size_t sizes[1];

  pid * key;
  icy_mem * key_area;
}pid_lookup;

pid_lookup * pid_lookup_create(const char * optional_name);
void pid_lookup_set(pid_lookup * table, pid key);
void pid_lookup_insert(pid_lookup * table, pid * key, size_t count);
void pid_lookup_lookup(pid_lookup * table, pid * keys, size_t * out_indexes, size_t count);
void pid_lookup_remove(pid_lookup * table, pid * keys, size_t key_count);
void pid_lookup_clear(pid_lookup * table);
void pid_lookup_unset(pid_lookup * table, pid key);
bool pid_lookup_try_get(pid_lookup * table, pid * key);
void pid_lookup_print(pid_lookup * table);
size_t pid_lookup_iter(pid_lookup * table, pid * keys, size_t keycnt, pid * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
