// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _pid_to_vec4{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const pid * k1, const pid * k2);
  const size_t sizes[2];

  pid * key;
  vec4 * value;
  icy_mem * key_area;
  icy_mem * value_area;
}pid_to_vec4;

pid_to_vec4 * pid_to_vec4_create(const char * optional_name);
void pid_to_vec4_set(pid_to_vec4 * table, pid key, vec4 value);
void pid_to_vec4_insert(pid_to_vec4 * table, pid * key, vec4 * value, size_t count);
void pid_to_vec4_lookup(pid_to_vec4 * table, pid * keys, size_t * out_indexes, size_t count);
void pid_to_vec4_remove(pid_to_vec4 * table, pid * keys, size_t key_count);
void pid_to_vec4_clear(pid_to_vec4 * table);
void pid_to_vec4_unset(pid_to_vec4 * table, pid key);
bool pid_to_vec4_try_get(pid_to_vec4 * table, pid * key, vec4 * value);
void pid_to_vec4_print(pid_to_vec4 * table);
size_t pid_to_vec4_iter(pid_to_vec4 * table, pid * keys, size_t keycnt, pid * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
