// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _u32_vector{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[1];
  
  u32 * values;
  icy_mem * values_area;
}u32_vector;

// a vector index.
typedef struct{
  size_t index;
}u32_vector_index;

typedef struct{
  size_t index;
  size_t count;
}u32_vector_indexes;

u32_vector * u32_vector_create(const char * optional_name);
u32_vector_index u32_vector_alloc(u32_vector * table);
u32_vector_indexes u32_vector_alloc_sequence(u32_vector * table, size_t count);
void u32_vector_remove(u32_vector * table, u32_vector_index index);
void u32_vector_remove_sequence(u32_vector * table, u32_vector_indexes * indexes);
void u32_vector_clear(u32_vector * table);
void u32_vector_optimize(u32_vector * table);
void u32_vector_destroy(u32_vector ** table);
