// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _u64_to_u8{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u64 * k1, const u64 * k2);
  const size_t sizes[2];

  u64 * key;
  u8 * value;
  icy_mem * key_area;
  icy_mem * value_area;
}u64_to_u8;

u64_to_u8 * u64_to_u8_create(const char * optional_name);
void u64_to_u8_set(u64_to_u8 * table, u64 key, u8 value);
void u64_to_u8_insert(u64_to_u8 * table, u64 * key, u8 * value, size_t count);
void u64_to_u8_lookup(u64_to_u8 * table, u64 * keys, size_t * out_indexes, size_t count);
void u64_to_u8_remove(u64_to_u8 * table, u64 * keys, size_t key_count);
void u64_to_u8_clear(u64_to_u8 * table);
void u64_to_u8_unset(u64_to_u8 * table, u64 key);
bool u64_to_u8_try_get(u64_to_u8 * table, u64 * key, u8 * value);
void u64_to_u8_print(u64_to_u8 * table);
size_t u64_to_u8_iter(u64_to_u8 * table, u64 * keys, size_t keycnt, u64 * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
