// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _window_table{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const windows_index * k1, const windows_index * k2);
  const size_t sizes[1];

  windows_index * id;
  icy_mem * id_area;
}window_table;

window_table * window_table_create(const char * optional_name);
void window_table_set(window_table * table, windows_index id);
void window_table_insert(window_table * table, windows_index * id, size_t count);
void window_table_lookup(window_table * table, windows_index * keys, size_t * out_indexes, size_t count);
void window_table_remove(window_table * table, windows_index * keys, size_t key_count);
void window_table_clear(window_table * table);
void window_table_unset(window_table * table, windows_index key);
bool window_table_try_get(window_table * table, windows_index * id);
void window_table_print(window_table * table);
size_t window_table_iter(window_table * table, windows_index * keys, size_t keycnt, windows_index * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
